name = "manic-pixie-dreamgirl"
author = "Wawwior"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46573758703e06edab1a5a3842c9710c465b786b196c761a4aecc82f8e149c96"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
