name = "manic-pixie-dreamgirl"
author = "Wawwior"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dee86ba4ed781bfe3db6e0c3f6d90b7906f8413b035e36e3c81a2d243aa2dc2e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
