name = "manic-pixie-dreamgirl"
author = "Wawwior"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72109b928db05f66c922cd2c98006cb2d86e825ed4d233bff1008041e81754fb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
